### ISSUE TITLE
Does verifyJWT require options.audience?

### ISSUE THREAD

**Issue by localredhead** [uport-project/did-jwt#11]
# Current Behavior
Using the `verifyJWT` function to verify a JWT.

I noticed in the `audience` parameter the `options` parameter is set to required `FALSE`, but I receive the error `JWT audience is required but your app address has not been configured`. when I do not set the `audience` parameter

Therefore I set `audience` parameter, to my DApps MNID, and everything works as expected.

```
verifyJWT(request.body.JWT, {
      audience: uportAppAddress // MNID of registered Decentralized Application.
    }).then(verifiedJWT => {
      console.log(verifiedJWT)
      ... // De more Things
    })
``` 
# Expected Behavior
If the audience parameter is not required in the options object, there should be no error.

# Failure Information

`JWT audience is required but your app address has not been configured`

**Comment by localredhead** [comment]
cc @KamesCG

**Comment by oed** [comment]
does the JWT contain an `aud` param? If so the audience parameter is optional, otherwise not.

**Comment by oed** [comment]
Does the JWT that you are trying to verify have a `aud` field? If so the audience is required, otherwise the audience is optional.

**Comment by zachferland** [comment]
related https://github.com/uport-project/did-jwt/issues/8

**Comment by pelle** [comment]
As @oed says it is only required if the JWT has an `aud` field
