### ISSUE TITLE
Audience optional in verification?

### ISSUE THREAD

**Issue by zachferland** [uport-project/did-jwt#8]
Since this is more of a core component, could it be it be less opinionated and allow audience checks to be optional and only check if audience or callback is passed in. Seems like for a did-jwt the core functionally is sig verification over payload for did (while expired check is a good default), while aud is secondary filters (over the payload) you may or may not want to use when verifying. 

One example where this is a pain to use is verifying the response from a uPort client for a simple address/did/id request. In this case there is no audience did, there is a callback, but its the messenger server chasqui with a random append string, so checking against that is not useful nor is decoding the response and passing it into this function just to get it to work. 

https://github.com/uport-project/did-jwt/blob/10df837635ef443bd9b54a982cfa5f8d2a844e58/src/JWT.js#L121-L138

**Comment by pelle** [comment]
Not checking this goes against the spec. The core issue you're mentioning @zachferland will be fixed anyway with the new libraries
